name: ${project.name}
version: ${project.version}
main: com.i0dev.loaders.LoadersPlugin
website: ${project.url}
authors: [ i01 ]
depend: [ MassiveCore, Factions, Citizens ]
description: ${project.description}
api-version: 1.20
permissions:
  loaders.basecommand: { description: loaders basecommand, default: false }
  loaders.version: { description: check version, default: false }
  loaders.*:
    loaders.basecommand: true
    loaders.version: true
  loaders.kit.op:
    default: op
    children:
      loaders.*: true
  loaders.kit.rank0:
    default: false
    children:
      loaders.basecommand: true
  loaders.kit.default:
    default: true
    children:
      loaders.kit.rank0: true